### ISSUE TITLE
Add compiled version to release

### ISSUE THREAD

**Issue by ktaranov** [sergeysyrovatchenko/SQLIndexManager#1]
Hi, @sergeysyrovatchenko 
Great thanks for very nice tool. Could you add compiled (.exe) version of tool in releases (I do not have VS installed on my laptop)?

**Comment by sergeysyrovatchenko** [comment]
Latest build of the master branch you can always get from [Google Disk](https://drive.google.com/open?id=15-dhScvyBfn-qJrb0izF6g1gXg3o40wH).

**Comment by sergeysyrovatchenko** [comment]
Done
