### ISSUE TITLE
Online=On doesn't seem to be working

### ISSUE THREAD

**Issue by plcos** [sergeysyrovatchenko/SQLIndexManager#10]
I have the Online=On flag active but when i run the index rebuild it used the Off option, and when i check the script it runs, the flag is off.

**Comment by sergeysyrovatchenko** [comment]
Please provide the definition of your tables and also check @@VERSION. Because in some cases this is a normal behavior. For example, you are using legacy LOB datatypes (ntext, text, image) or your SQL Server edition is non-Enterprise.

**Comment by plcos** [comment]
Hello Sergy, i'm using Azure SQL which supports Online. I run it without
any problems with orther scripts.

A sexta, 6/09/2019, 13:40, Sergey Syrovatchenko <notifications@github.com>
escreveu:

**Comment by sergeysyrovatchenko** [comment]
Fixed in version 1.0.0.52. Thanks for your feedback.
