### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by Almeonamy** [sergeysyrovatchenko/SQLIndexManager#15]
Hello. Didn't you think about to create nuget-package from this project? We want to use it to automate nightly defragmentation, and we want to call it from .net app. Yes, we can put the binaries on the server and call it by the command line. But it doesn't look good.

**Comment by sergeysyrovatchenko** [comment]
Hi. Maybe in future, but currently - as design. Next changes: multi-server maintenance at the same time
