### ISSUE TITLE
Feature Request : show  all indexes

### ISSUE THREAD

**Issue by crevecoeurj** [sergeysyrovatchenko/SQLIndexManager#16]
The index screen is very useful .

Add an option to see all indexes with 0% fragmentation was great.

Thanks for your work.

**Comment by sergeysyrovatchenko** [comment]
Hi. Thanks for your feedback.
You can achieve the expected behavior if changed fragmentation filter to 0%.

**Comment by sergeysyrovatchenko** [comment]
Feature in progress

**Comment by sergeysyrovatchenko** [comment]
Implemented in v1.0.0.56. Thanks for your feedback.

**Comment by edo1** [comment]
Do not see a way to avoid filtering out huge indexes (over 128GB)
