### ISSUE TITLE
No option to use existing index options on rebuild etc?

### ISSUE THREAD

**Issue by edwillis777** [sergeysyrovatchenko/SQLIndexManager#17]
Great tool

Just as a DBA I want to keep the index settings already on the index when I perform maintenance. Like Data Compression, Fill Factor Pad Index etc. If you can add an option to use existing this would be a great tool.

**Comment by sergeysyrovatchenko** [comment]
In current implementation all default settings inherit standard index properties (DATA_COMPRESSION, FILLFACTOR, etc.) when you trying to get information about index fragmentation.

**Comment by edwillis777** [comment]
I guess I must be confused, when I run the tool it seems to take what is set in the defaults when rebuilding indexes and not what the index is already set to for data compression etc.?

**Comment by sergeysyrovatchenko** [comment]
Can you please provide any repro with actual and excepted results? Thanks

**Comment by edwillis777** [comment]
![settings](https://user-images.githubusercontent.com/17711862/71095412-8dfb3a00-217a-11ea-92dc-02454f78764f.jpg)
I attached the settings here is the script your tool created:
USE [QA10]
GO

RAISERROR(N'QA10 | dbo.tablex | XAK1tablex | 10.66 MB', 0, 1) WITH NOWAIT
ALTER INDEX [XAKtablex] ON [dbo].[tablex] REBUILD PARTITION = ALL
    WITH (SORT_IN_TEMPDB = ON, PAD_INDEX = ON, FILLFACTOR = 90, DATA_COMPRESSION = PAGE, ONLINE = ON, MAXDOP = 0);
GO

The index properties in SQL Server are:
fill_factor
100
data_compression_desc
NONE
is_padded
0

So your tool used the settings for rebuild and if we can add an option to rebuild and use current index properties

Thanks.

**Comment by sergeysyrovatchenko** [comment]
Hi. Sorry for being late in answering you.
Settings was inherited globally for all indexes that app detects, so your situation is a completely correct.

Do I understand you correctly: your are changed settings, but in some cases want rebuild with default options "as is" inside index?

**Comment by edwillis777** [comment]
An option that will ignore the settings and simply rebuild the index with what the index has already set. Yes, this will allow indexes with different settings to be rebuilt correctly and not be rebuilt with the settings.

**Comment by sergeysyrovatchenko** [comment]
Partially fixed in v1.0.0.57 (data compression not apply if you choose REBUILD without any additional options)
