### ISSUE TITLE
Create extension for azure data studio.

### ISSUE THREAD

**Issue by lucasfolino** [sergeysyrovatchenko/SQLIndexManager#3]
I like what you are doing here.  I am not sure how hard or worth it, but do you think it would be possible or worth porting this to Azure Data Studio as an extension?  I think this would allow for more wide adoption and use.  If a lot of the logic is in SQL and just using dotnet to make calls it may be worth investigating.  If this would be a substantial rewrite or not what you are interested in then ignore this.    I just wanted to bring this up since I think this type of functionality would be amazing as a plugin for Azure Data Studio.  It would be cross platform, and already have a standard UI.

**Comment by sergeysyrovatchenko** [comment]
Thanks for the feedback. But this functionality was not planned initially.
