### ISSUE TITLE
Could not find table or object ID ... Check system catalog

### ISSUE THREAD

**Issue by WebSuburbFTV** [sergeysyrovatchenko/SQLIndexManager#35]
Firstly, this is a really great tool. Easy to use.
The app has worked successfully many times but now raises this error dialog:
"Could not find table or object ID 209435820
Check system catalog"
when either selects the database or the refresh button.

![image](https://user-images.githubusercontent.com/54554297/182037926-f1c40869-d5b0-4d6d-a260-a49cd9a2e00e.png)

I suspect that this is likely an issue in the database.

**Comment by sergiisyrovatchenko** [comment]
Hi @WebSuburbFTV 

Please take a look if everything fine with your system/user database: `DBCC CHECKDB (...)` and provide the output if possible.

Thanks!

**Comment by sergiisyrovatchenko** [comment]
Please re-open if still actual. Thanks!
