### ISSUE TITLE
Error retrieving index list

### ISSUE THREAD

**Issue by dartNNN** [sergeysyrovatchenko/SQLIndexManager#4]
1. Error in log:

Pre-describe #0 failed: <>. Rescan...
Arithmetic overflow error for data type tinyint, value = 398.
The statement has been terminated.
Warning: Null value is eliminated by an aggregate or other SET operation.

2. Noninformative message on error: "No indexes found". 

UPD:
after small debug:

    diff --git a/Server/Query.cs b/Server/Query.cs
    index 232d5fa..8b6b47a 100644
    --- a/Server/Query.cs
    +++ b/Server/Query.cs
    @@ -133,7 +133,7 @@ CREATE TABLE #IndexColumns (
           ObjectID      INT NOT NULL
         , IndexID       INT NOT NULL
         , IndexColumnID INT NOT NULL
    -    , ColumnID      TINYINT NOT NULL
    +    , ColumnID      INT NOT NULL
         , IsIncluded    BIT NOT NULL
         , PRIMARY KEY (ObjectID, IndexID, ColumnID)
     )

**Comment by sergeysyrovatchenko** [comment]
Already fixed by last commit. Please download v1.0.0.42. Thanks.
