### ISSUE TITLE
No indexes found

### ISSUE THREAD

**Issue by ShaneZhengNZ** [sergeysyrovatchenko/SQLIndexManager#6]
No matter which database I connect to, local MSSQL database or Azure SQL database. I always get 'No indexes found'.

Thoughts?

**Comment by GeoMac1313** [comment]
Set the minimum index size filter to 0 MB in Settings.  Then rescan your databases.  I have about a dozen test databases with very small index sizes so the same thing happened to me.

**Comment by sergeysyrovatchenko** [comment]
Do you checked settings? BTW, indexes where rows = 0 always ignored.

**Comment by ShaneZhengNZ** [comment]
@GeoMac1313 Thank you. The minimum size filter set to 0 fixed the issue.

**Comment by ShaneZhengNZ** [comment]
@sergeysyrovatchenko I would suggest that the minimum size filter default should be 0?

**Comment by sergeysyrovatchenko** [comment]
Minimal size (6...8Mb)  of index is set up by performance reasons. In common case it's a bad idea for OLTP databases.
