### ISSUE TITLE
Cmd command for autocreate indexes

### ISSUE THREAD

**Issue by msshubin** [sergeysyrovatchenko/SQLIndexManager#9]
Hi, can you add key/param in cmd for autocreate indexes?

**Comment by sergeysyrovatchenko** [comment]
Hi. What do you mean when talked about autocreate indexes? This is a missing indexes?

**Comment by msshubin** [comment]
In Settings/Object Scan i can check **Missing Index** and then, when i click Fix - it will be created in GUI. I want this option in cmd.

**Comment by sergeysyrovatchenko** [comment]
Ok. Will be ready in next release.

**Comment by msshubin** [comment]
Спасибо!

**Comment by sergeysyrovatchenko** [comment]
Please check v1.0.0.51: added new command line option - /missingindex
